package T;

import Bb.q;
import T0.l;
import T0.w;
import T0.y;

public abstract class j {
    public static final long A;
    public static final long B;
    public static final long C;
    public static final w D;
    public static final y E;
    public static final long F;
    public static final long G;
    public static final long H;
    public static final w I;
    public static final y J;
    public static final long K;
    public static final long L;
    public static final long M;
    public static final w N;
    public static final y O;
    public static final long P;
    public static final long Q;
    public static final long R;
    public static final w S;
    public static final y T;
    public static final long U;
    public static final long V;
    public static final long W;
    public static final w X;
    public static final y Y;
    public static final long Z;
    public static final y a;
    public static final long a0;
    public static final long b;
    public static final long b0;
    public static final long c;
    public static final w c0;
    public static final long d;
    public static final y d0;
    public static final w e;
    public static final long e0;
    public static final y f;
    public static final long f0;
    public static final long g;
    public static final long g0;
    public static final long h;
    public static final w h0;
    public static final long i;
    public static final y i0;
    public static final w j;
    public static final long j0;
    public static final y k;
    public static final long k0;
    public static final long l;
    public static final long l0;
    public static final long m;
    public static final w m0;
    public static final long n;
    public static final y n0;
    public static final w o;
    public static final long o0;
    public static final y p;
    public static final long p0;
    public static final long q;
    public static final long q0;
    public static final long r;
    public static final w r0;
    public static final long s;
    public static final y s0;
    public static final w t;
    public static final long t0;
    public static final y u;
    public static final long u0;
    public static final long v;
    public static final long v0;
    public static final long w;
    public static final w w0;
    public static final long x;
    public static final w y;
    public static final y z;

    static {
        y y0 = l.Y;
        j.a = y0;
        j.b = q.B(24.0);
        j.c = q.C(16);
        j.d = q.B(0.5);
        w w0 = k.b;
        j.e = w0;
        j.f = y0;
        j.g = q.B(20.0);
        j.h = q.C(14);
        j.i = q.B(0.2);
        j.j = w0;
        j.k = y0;
        j.l = q.B(16.0);
        j.m = q.C(12);
        j.n = q.B(0.4);
        j.o = w0;
        j.p = y0;
        j.q = q.B(64.0);
        j.r = q.C(57);
        long v = q.B(0.2);
        if(q.H(v)) {
            throw new IllegalArgumentException("Cannot perform operation for Unspecified type.");
        }
        j.s = q.P(-a1.j.c(v), v & 0xFF00000000L);
        j.t = w0;
        j.u = y0;
        j.v = q.B(52.0);
        j.w = q.C(45);
        j.x = q.B(0.0);
        j.y = w0;
        j.z = y0;
        j.A = q.B(44.0);
        j.B = q.C(36);
        j.C = q.B(0.0);
        j.D = w0;
        j.E = y0;
        j.F = q.B(40.0);
        j.G = q.C(0x20);
        j.H = q.B(0.0);
        j.I = w0;
        j.J = y0;
        j.K = q.B(36.0);
        j.L = q.C(28);
        j.M = q.B(0.0);
        j.N = w0;
        j.O = y0;
        j.P = q.B(32.0);
        j.Q = q.C(24);
        j.R = q.B(0.0);
        j.S = w0;
        j.T = y0;
        j.U = q.B(20.0);
        j.V = q.C(14);
        j.W = q.B(0.1);
        j.X = k.a;
        j.Y = y0;
        j.Z = q.B(16.0);
        j.a0 = q.C(12);
        j.b0 = q.B(0.5);
        j.c0 = k.a;
        j.d0 = y0;
        j.e0 = q.B(16.0);
        j.f0 = q.C(11);
        j.g0 = q.B(0.5);
        j.h0 = k.a;
        j.i0 = y0;
        j.j0 = q.B(28.0);
        j.k0 = q.C(22);
        j.l0 = q.B(0.0);
        j.m0 = w0;
        j.n0 = y0;
        j.o0 = q.B(24.0);
        j.p0 = q.C(16);
        j.q0 = q.B(0.2);
        j.r0 = k.a;
        j.s0 = y0;
        j.t0 = q.B(20.0);
        j.u0 = q.C(14);
        j.v0 = q.B(0.1);
        j.w0 = k.a;
    }
}

