package j6;

import H6.e;
import L7.b;
import io.sentry.hints.i;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import v7.d;

public abstract class s {
    public static final A A;
    public static final A A0;
    public static final A B;
    public static final A B0;
    public static final A C;
    public static final A C0;
    public static final A D;
    public static final A D0;
    public static final A E;
    public static final A E0;
    public static final A F;
    public static final A F0;
    public static final A G;
    public static final A G0;
    public static final A H;
    public static final A H0;
    public static final A I;
    public static final A I0;
    public static final A J;
    public static final A J0;
    public static final A K;
    public static final A K0;
    public static final A L;
    public static final A L0;
    public static final A M;
    public static final A M0;
    public static final A N;
    public static final A N0;
    public static final A O;
    public static final A O0;
    public static final A P;
    public static final A P0;
    public static final A Q;
    public static final A Q0;
    public static final A R;
    public static final A R0;
    public static final A S;
    public static final A S0;
    public static final A T;
    public static final A T0;
    public static final A U;
    public static final A U0;
    public static final A V;
    public static final A V0;
    public static final A W;
    public static final A W0;
    public static final A X;
    public static final A X0;
    public static final A Y;
    public static final A Y0;
    public static final A Z;
    public static final A Z0;
    public static final List a;
    public static final A a0;
    public static final A a1;
    public static final A b;
    public static final A b0;
    public static final A b1;
    public static final A c;
    public static final A c0;
    public static final A c1;
    public static final A d;
    public static final A d0;
    public static final A d1;
    public static final A e;
    public static final A e0;
    public static final A e1;
    public static final A f;
    public static final A f0;
    public static final A f1;
    public static final A g;
    public static final A g0;
    public static final A g1;
    public static final A h;
    public static final A h0;
    public static final A h1;
    public static final A i;
    public static final A i0;
    public static final A i1;
    public static final A j;
    public static final A j0;
    public static final A j1;
    public static final A k;
    public static final A k0;
    public static final A k1;
    public static final A l;
    public static final A l0;
    public static final A l1;
    public static final A m;
    public static final A m0;
    public static final A n;
    public static final A n0;
    public static final A o;
    public static final A o0;
    public static final A p;
    public static final A p0;
    public static final A q;
    public static final A q0;
    public static final A r;
    public static final A r0;
    public static final A s;
    public static final A s0;
    public static final A t;
    public static final A t0;
    public static final A u;
    public static final A u0;
    public static final A v;
    public static final A v0;
    public static final A w;
    public static final A w0;
    public static final A x;
    public static final A x0;
    public static final A y;
    public static final A y0;
    public static final A z;
    public static final A z0;

    static {
        s.a = Collections.synchronizedList(new ArrayList());
        Collections.synchronizedSet(new HashSet());
        Long long0 = 10000L;
        s.b = s.a("measurement.ad_id_cache_time", long0, new e(26), false);
        s.c = s.a("measurement.app_uninstalled_additional_ad_id_cache_time", 3600000L, new v(6), false);
        s.d = s.a("measurement.monitoring.sample_period_millis", 86400000L, new v(9), false);
        s.e = s.a("measurement.config.cache_time", 86400000L, new v(12), false);
        s.f = s.a("measurement.config.url_scheme", "https", new v(15), false);
        s.g = s.a("measurement.config.url_authority", "app-measurement.com", new v(18), false);
        s.h = s.a("measurement.upload.max_bundles", 100, new v(21), false);
        s.i = s.a("measurement.upload.max_batch_size", 0x10000, new v(24), false);
        s.j = s.a("measurement.upload.max_bundle_size", 0x10000, new i(28), false);
        s.k = s.a("measurement.upload.max_events_per_bundle", 1000, new w(1), false);
        s.l = s.a("measurement.upload.max_events_per_day", 100000, new v(1), false);
        s.m = s.a("measurement.upload.max_error_events_per_day", 1000, new x(3), false);
        s.n = s.a("measurement.upload.max_public_events_per_day", 50000, new w(4), false);
        s.o = s.a("measurement.upload.max_conversions_per_day", 10000, new v(4), false);
        s.p = s.a("measurement.upload.max_realtime_events_per_day", 10, new u(5), false);
        s.q = s.a("measurement.store.max_stored_events_per_app", 100000, new x(4), false);
        s.r = s.a("measurement.upload.url", "https://app-measurement.com/a", new w(5), false);
        s.s = s.a("measurement.sgtm.google_signal.url", "https://app-measurement.com/s", new v(5), false);
        s.t = s.a("measurement.upload.backoff_period", 43200000L, new u(6), false);
        s.u = s.a("measurement.upload.window_interval", 3600000L, new x(5), false);
        s.v = s.a("measurement.upload.interval", 3600000L, new u(7), false);
        s.w = s.a("measurement.upload.realtime_upload_interval", long0, new x(6), false);
        s.x = s.a("measurement.upload.debug_upload_interval", 1000L, new w(7), false);
        s.y = s.a("measurement.upload.minimum_delay", 500L, new v(7), false);
        s.z = s.a("measurement.alarm_manager.minimum_interval", 60000L, new u(8), false);
        s.A = s.a("measurement.upload.stale_data_deletion_interval", 86400000L, new x(7), false);
        s.B = s.a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, new w(8), false);
        s.C = s.a("measurement.upload.initial_upload_delay_time", 15000L, new v(8), false);
        s.D = s.a("measurement.upload.retry_time", 1800000L, new u(9), false);
        s.E = s.a("measurement.upload.retry_count", 6, new w(9), false);
        s.F = s.a("measurement.upload.max_queue_time", 518400000L, new u(10), false);
        s.G = s.a("measurement.upload.google_signal_max_queue_time", 300000L, new x(9), false);
        s.H = s.a("measurement.lifetimevalue.max_currency_tracked", 4, new w(10), false);
        s.I = s.a("measurement.audience.filter_result_max_count", 200, new v(10), false);
        s.J = s.a("measurement.upload.max_public_user_properties", 100, null, false);
        s.K = s.a("measurement.upload.max_event_name_cardinality", 2000, null, false);
        s.L = s.a("measurement.upload.max_public_event_params", 100, null, false);
        s.M = s.a("measurement.service_client.idle_disconnect_millis", 5000L, new u(11), false);
        Boolean boolean0 = Boolean.FALSE;
        s.N = s.a("measurement.test.boolean_flag", boolean0, new x(10), false);
        s.O = s.a("measurement.test.string_flag", "---", new w(11), false);
        s.P = s.a("measurement.test.long_flag", -1L, new v(11), false);
        s.a("measurement.test.cached_long_flag", -1L, new x(11), true);
        s.Q = s.a("measurement.test.int_flag", -2, new w(12), false);
        s.R = s.a("measurement.test.double_flag", -3.0, new u(13), false);
        s.S = s.a("measurement.experiment.max_ids", 50, new x(12), false);
        s.T = s.a("measurement.upload.max_item_scoped_custom_parameters", 27, new w(13), false);
        s.U = s.a("measurement.upload.max_event_parameter_value_length", 500, new v(13), true);
        s.V = s.a("measurement.max_bundles_per_iteration", 100, new u(14), false);
        s.W = s.a("measurement.sdk.attribution.cache.ttl", 604800000L, new x(13), false);
        s.X = s.a("measurement.redaction.app_instance_id.ttl", 7200000L, new w(14), false);
        s.Y = s.a("measurement.rb.attribution.client.min_ad_services_version", 7, new u(15), false);
        s.Z = s.a("measurement.dma_consent.max_daily_dcu_realtime_events", 1, new x(14), false);
        s.a0 = s.a("measurement.rb.attribution.uri_scheme", "https", new w(15), false);
        s.b0 = s.a("measurement.rb.attribution.uri_authority", "google-analytics.com", new u(16), false);
        s.c0 = s.a("measurement.rb.attribution.uri_path", "privacy-sandbox/register-app-conversion", new x(15), false);
        s.d0 = s.a("measurement.session.engagement_interval", 3600000L, new w(16), false);
        s.e0 = s.a("measurement.rb.attribution.app_allowlist", "com.labpixies.flood,com.sofascore.results,games.spearmint.triplecrush,com.block.juggle,io.supercent.linkedcubic,com.cdtg.gunsound,com.corestudios.storemanagementidle,com.cdgames.fidget3d,io.supercent.burgeridle,io.supercent.pizzaidle,jp.ne.ibis.ibispaintx.app,com.dencreak.dlcalculator,com.ebay.kleinanzeigen,de.wetteronline.wetterapp,com.game.shape.shift,com.champion.cubes,bubbleshooter.orig,com.wolt.android,com.master.hotelmaster,com.games.bus.arrival,com.playstrom.dop2,com.huuuge.casino.slots,com.ig.spider.fighting,com.jura.coloring.page,com.rikkogame.ragdoll2,com.ludo.king,com.sigma.prank.sound.haircut,com.crazy.block.robo.monster.cliffs.craft,com.fugo.wow,com.maps.locator.gps.gpstracker.phone,com.gamovation.tileclub,com.pronetis.ironball2,com.meesho.supply,pdf.pdfreader.viewer.editor.free,com.dino.race.master,com.ig.moto.racing,ai.photo.enhancer.photoclear,com.duolingo,com.candle.magic_piano,com.free.vpn.super.hotspot.open,sg.bigo.live,com.cdg.tictactoe,com.zhiliaoapp.musically.go,com.wildspike.wormszone,com.mast.status.video.edit,com.vyroai.photoeditorone,com.pujiagames.deeeersimulator,com.superbinogo.jungleboyadventure,com.trustedapp.pdfreaderpdfviewer,com.artimind.aiart.artgenerator.artavatar,de.cellular.ottohybrid,com.zeptolab.cats.google,in.crossy.daily_crossword", new v(16), false);
        s.f0 = s.a("measurement.rb.attribution.user_properties", "_npa,npa|_fot,fot", new u(17), false);
        s.g0 = s.a("measurement.rb.attribution.event_params", "value|currency", new x(16), false);
        s.h0 = s.a("measurement.rb.attribution.query_parameters_to_remove", "", new v(17), false);
        s.i0 = s.a("measurement.rb.attribution.max_queue_time", 1209600000L, new u(18), false);
        s.a("measurement.rb.attribution.max_trigger_uris_queried_at_once", 0, new x(17), false);
        s.j0 = s.a("measurement.rb.max_trigger_registrations_per_day", 0, new w(18), false);
        Boolean boolean1 = Boolean.TRUE;
        s.k0 = s.a("measurement.config.bundle_for_all_apps_on_backgrounded", boolean1, new u(19), false);
        s.l0 = s.a("measurement.config.notify_trigger_uris_on_backgrounded", boolean1, new x(18), false);
        s.a("measurement.collection.log_event_and_bundle_v2", boolean1, new w(19), false);
        s.m0 = s.a("measurement.quality.checksum", boolean0, null, false);
        s.n0 = s.a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", boolean0, new v(19), false);
        s.o0 = s.a("measurement.audience.refresh_event_count_filters_timestamp", boolean0, new u(20), false);
        s.p0 = s.a("measurement.audience.use_bundle_timestamp_for_event_count_filters", boolean0, new w(20), true);
        s.q0 = s.a("measurement.sdk.collection.last_deep_link_referrer_campaign2", boolean0, new v(20), false);
        s.r0 = s.a("measurement.integration.disable_firebase_instance_id", boolean0, new u(21), false);
        s.s0 = s.a("measurement.collection.service.update_with_analytics_fix", boolean0, new x(20), false);
        s.t0 = s.a("measurement.service.storage_consent_support_version", 203600, new w(21), false);
        s.u0 = s.a("measurement.service.store_null_safelist", boolean1, new u(22), false);
        s.v0 = s.a("measurement.service.store_safelist", boolean1, new x(21), false);
        s.w0 = s.a("measurement.session_stitching_token_enabled", boolean0, new w(22), false);
        s.x0 = s.a("measurement.sgtm.service", boolean1, new v(22), true);
        s.y0 = s.a("measurement.sgtm.preview_mode_enabled", boolean1, new x(22), true);
        s.z0 = s.a("measurement.sgtm.rollout_percentage_fix", boolean0, new w(23), true);
        s.A0 = s.a("measurement.sgtm.app_allowlist", "de.zalando.mobile.internal,de.zalando.mobile.internal.debug,de.zalando.lounge.dev,grit.storytel.app,com.rbc.mobile.android,com.rbc.mobile.android,com.dylvian.mango.activities,com.home24.android,com.home24.android.staging,se.lf.mobile.android,se.lf.mobile.android.beta,se.lf.mobile.android.rc,se.lf.mobile.android.test,se.lf.mobile.android.test.debug,com.boots.flagship.android,com.boots.flagshiproi.android,de.zalando.mobile,com.trivago,com.getyourguide.android,es.mobail.meliarewards,se.nansen.coop.debug,se.nansen.coop,se.coop.coop.qa,com.booking,com.google.firebaseengage,com.mse.mseapp.dev,com.mse.mseapp,pl.eobuwie.eobuwieapp,br.com.eventim.mobile.app.Android,ch.ticketcorner.mobile.app.Android,de.eventim.mobile.app.Android,dk.billetlugen.mobile.app.Android,nl.eventim.mobile.app.Android,com.asos.app,com.blueshieldca.prod,dk.magnetix.tivoliapp,matas.matas.internal,nl.omoda,com.thetrainline,com.simo.androidtest,de.aboutyou.mobile.app,com.hometogo,de.casamundo.casamundomobile,it.casevacanz,eu.coolblue.shop,com.stihl.app,com.indeed.android.jobsearch,com.homeretailgroup.argos.android,com.dylvian.mango.activities.pre,se.nansen.coop.qa", new v(23), true);
        s.B0 = s.a("measurement.sgtm.upload_queue", boolean0, new u(24), false);
        s.C0 = s.a("measurement.sgtm.google_signal.enable", boolean0, new x(23), false);
        s.D0 = s.a("measurement.gmscore_feature_tracking", boolean1, new w(24), false);
        s.E0 = s.a("measurement.gmscore_client_telemetry", boolean0, new u(25), false);
        s.F0 = s.a("measurement.gmscore_network_migration", boolean0, new x(24), false);
        s.G0 = s.a("measurement.fix_health_monitor_stack_trace", boolean1, new v(25), true);
        s.H0 = s.a("measurement.rb.attribution.service", boolean1, new b(26), true);
        s.I0 = s.a("measurement.rb.attribution.client2", boolean1, new e(27), true);
        s.J0 = s.a("measurement.rb.attribution.uuid_generation", boolean1, new d(26), false);
        s.K0 = s.a("measurement.rb.attribution.enable_trigger_redaction", boolean1, new i(27), false);
        Boolean boolean2 = Boolean.FALSE;
        s.a("measurement.rb.attribution.followup1.service", boolean2, new b(27), false);
        s.L0 = s.a("measurement.rb.attribution.retry_disposition", boolean2, new e(28), false);
        s.M0 = s.a("measurement.rb.attribution.ad_campaign_info", boolean2, new d(27), false);
        s.N0 = s.a("measurement.rb.attribution.improved_retry", boolean1, new b(28), true);
        s.O0 = s.a("measurement.client.sessions.enable_fix_background_engagement", boolean2, new e(29), false);
        s.P0 = s.a("measurement.client.sessions.enable_pause_engagement_in_background", boolean1, new i(29), false);
        s.Q0 = s.a("measurement.dma_consent.service_dcu_event2", boolean1, new b(29), false);
        s.R0 = s.a("measurement.dma_consent.services_database_update_fix", boolean1, new u(0), false);
        s.S0 = s.a("measurement.dma_consent.setting_npa_inline_fix", boolean1, new d(29), false);
        s.T0 = s.a("measurement.gbraid_campaign.gbraid.client", boolean1, new w(0), true);
        s.U0 = s.a("measurement.gbraid_campaign.gbraid.service", boolean1, new v(0), true);
        s.V0 = s.a("measurement.service.consent.pfo_on_fx", boolean1, new u(1), false);
        s.W0 = s.a("measurement.service.consent.params_on_fx", boolean1, new x(0), false);
        s.X0 = s.a("measurement.consent.stop_reset_on_storage_denied.client", boolean1, new v(3), true);
        s.Y0 = s.a("measurement.consent.stop_reset_on_storage_denied.service", boolean1, new w(6), true);
        s.Z0 = s.a("measurement.consent.scrub_audience_data_analytics_consent", boolean1, new x(8), false);
        s.a1 = s.a("measurement.consent.fix_first_open_count_from_snapshot", boolean1, new u(12), false);
        s.b1 = s.a("measurement.fix_engagement_on_reset_analytics_data", boolean1, new v(14), false);
        s.c1 = s.a("measurement.rb.attribution.service.bundle_on_backgrounded", boolean1, new w(17), false);
        s.d1 = s.a("measurement.rb.attribution.client.bundle_on_backgrounded", boolean1, new x(19), false);
        s.e1 = s.a("measurement.set_default_event_parameters_propagate_clear.service.dev", boolean2, new u(23), false);
        s.f1 = s.a("measurement.set_default_event_parameters_propagate_clear.client.dev", boolean2, new i(26), false);
        s.g1 = s.a("measurement.set_default_event_parameters_with_backfill.service", boolean2, new d(28), false);
        s.a("measurement.set_default_event_parameters_with_backfill.client.dev", boolean2, new u(2), false);
        Boolean boolean3 = Boolean.TRUE;
        s.h1 = s.a("measurement.defensively_copy_bundles_validate_default_params", boolean3, new x(1), false);
        s.i1 = s.a("measurement.fix_origin_in_upload_utils.service", boolean3, new w(2), false);
        s.a("measurement.chimera.parameter.service", boolean3, new v(2), false);
        s.j1 = s.a("measurement.service.ad_impression.convert_value_to_double", boolean3, new u(3), false);
        s.k1 = s.a("measurement.persisted_config_defensive_copies", boolean2, new x(2), false);
        s.a("measurement.rb.attribution.service.enable_max_trigger_uris_queried_at_once", boolean3, new w(3), false);
        s.l1 = s.a("measurement.currency.escape_underscore_fix", boolean3, new u(4), false);
    }

    public static A a(String s, Object object0, z z0, boolean z1) {
        A a0 = new A(s, object0, z0);
        if(z1) {
            s.a.add(a0);
        }
        return a0;
    }
}

