package com.drew.metadata.exif;

import com.drew.metadata.b;
import java.util.HashMap;

public abstract class ExifDirectoryBase extends b {
    public static final int TAG_35MM_FILM_EQUIV_FOCAL_LENGTH = 0xA405;
    public static final int TAG_ACCELERATION = 0x9404;
    public static final int TAG_APERTURE = 0x9202;
    public static final int TAG_APPLICATION_NOTES = 700;
    public static final int TAG_ARTIST = 315;
    public static final int TAG_BATTERY_LEVEL = 0x828F;
    public static final int TAG_BITS_PER_SAMPLE = 0x102;
    public static final int TAG_BODY_SERIAL_NUMBER = 42033;
    public static final int TAG_BRIGHTNESS_VALUE = 0x9203;
    public static final int TAG_CAMERA_ELEVATION_ANGLE = 0x9405;
    public static final int TAG_CAMERA_OWNER_NAME = 0xA430;
    public static final int TAG_CFA_PATTERN = 0xA302;
    public static final int TAG_CFA_PATTERN_2 = 0x828E;
    public static final int TAG_CFA_REPEAT_PATTERN_DIM = 0x828D;
    public static final int TAG_COLOR_SPACE = 0xA001;
    public static final int TAG_COMPONENTS_CONFIGURATION = 0x9101;
    public static final int TAG_COMPRESSED_AVERAGE_BITS_PER_PIXEL = 0x9102;
    public static final int TAG_COMPRESSION = 0x103;
    public static final int TAG_CONTRAST = 0xA408;
    public static final int TAG_COPYRIGHT = 0x8298;
    public static final int TAG_CUSTOM_RENDERED = 0xA401;
    public static final int TAG_DATETIME = 306;
    public static final int TAG_DATETIME_DIGITIZED = 0x9004;
    public static final int TAG_DATETIME_ORIGINAL = 0x9003;
    public static final int TAG_DEVICE_SETTING_DESCRIPTION = 0xA40B;
    public static final int TAG_DIGITAL_ZOOM_RATIO = 0xA404;
    public static final int TAG_DOCUMENT_NAME = 0x10D;
    public static final int TAG_EXIF_IMAGE_HEIGHT = 0xA003;
    public static final int TAG_EXIF_IMAGE_WIDTH = 0xA002;
    public static final int TAG_EXIF_VERSION = 0x9000;
    public static final int TAG_EXPOSURE_BIAS = 0x9204;
    public static final int TAG_EXPOSURE_INDEX = 0xA215;
    public static final int TAG_EXPOSURE_INDEX_TIFF_EP = 0x9215;
    public static final int TAG_EXPOSURE_MODE = 0xA402;
    public static final int TAG_EXPOSURE_PROGRAM = 34850;
    public static final int TAG_EXPOSURE_TIME = 0x829A;
    public static final int TAG_EXTRA_SAMPLES = 338;
    public static final int TAG_FILE_SOURCE = 0xA300;
    public static final int TAG_FILL_ORDER = 0x10A;
    public static final int TAG_FLASH = 0x9209;
    public static final int TAG_FLASHPIX_VERSION = 0xA000;
    public static final int TAG_FLASH_ENERGY = 0xA20B;
    public static final int TAG_FLASH_ENERGY_TIFF_EP = 0x920B;
    public static final int TAG_FNUMBER = 0x829D;
    public static final int TAG_FOCAL_LENGTH = 0x920A;
    public static final int TAG_FOCAL_PLANE_RESOLUTION_UNIT = 0xA210;
    public static final int TAG_FOCAL_PLANE_X_RESOLUTION = 0xA20E;
    public static final int TAG_FOCAL_PLANE_X_RESOLUTION_TIFF_EP = 0x920E;
    public static final int TAG_FOCAL_PLANE_Y_RESOLUTION = 0xA20F;
    public static final int TAG_FOCAL_PLANE_Y_RESOLUTION_TIFF_EP = 0x920F;
    public static final int TAG_GAIN_CONTROL = 0xA407;
    public static final int TAG_GAMMA = 0xA500;
    public static final int TAG_HOST_COMPUTER = 316;
    public static final int TAG_HUMIDITY = 0x9401;
    public static final int TAG_IMAGE_DESCRIPTION = 270;
    public static final int TAG_IMAGE_HEIGHT = 0x101;
    public static final int TAG_IMAGE_HISTORY = 0x9213;
    public static final int TAG_IMAGE_NUMBER = 0x9211;
    public static final int TAG_IMAGE_UNIQUE_ID = 0xA420;
    public static final int TAG_IMAGE_WIDTH = 0x100;
    public static final int TAG_INTERLACE = 0x8829;
    public static final int TAG_INTEROP_INDEX = 1;
    public static final int TAG_INTEROP_VERSION = 2;
    public static final int TAG_INTER_COLOR_PROFILE = 0x8773;
    public static final int TAG_IPTC_NAA = 0x83BB;
    public static final int TAG_ISO_EQUIVALENT = 0x8827;
    public static final int TAG_ISO_SPEED = 0x8833;
    public static final int TAG_ISO_SPEED_LATITUDE_YYY = 0x8834;
    public static final int TAG_ISO_SPEED_LATITUDE_ZZZ = 0x8835;
    public static final int TAG_JPEG_AC_TABLES = 0x209;
    public static final int TAG_JPEG_DC_TABLES = 520;
    public static final int TAG_JPEG_LOSSLESS_PREDICTORS = 0x205;
    public static final int TAG_JPEG_POINT_TRANSFORMS = 0x206;
    public static final int TAG_JPEG_PROC = 0x200;
    public static final int TAG_JPEG_Q_TABLES = 0x207;
    public static final int TAG_JPEG_RESTART_INTERVAL = 0x203;
    public static final int TAG_JPEG_TABLES = 347;
    public static final int TAG_LENS = 65002;
    public static final int TAG_LENS_MAKE = 42035;
    public static final int TAG_LENS_MODEL = 42036;
    public static final int TAG_LENS_SERIAL_NUMBER = 42037;
    public static final int TAG_LENS_SPECIFICATION = 42034;
    @Deprecated
    public static final int TAG_LIGHT_SOURCE = 0x9208;
    public static final int TAG_MAKE = 0x10F;
    public static final int TAG_MAKERNOTE = 37500;
    public static final int TAG_MAX_APERTURE = 0x9205;
    public static final int TAG_MAX_SAMPLE_VALUE = 281;
    public static final int TAG_METERING_MODE = 0x9207;
    public static final int TAG_MIN_SAMPLE_VALUE = 280;
    public static final int TAG_MODEL = 0x110;
    public static final int TAG_NEW_SUBFILE_TYPE = 0xFE;
    public static final int TAG_NOISE = 0x920D;
    public static final int TAG_OPTO_ELECTRIC_CONVERSION_FUNCTION = 0x8828;
    public static final int TAG_ORIENTATION = 274;
    public static final int TAG_PADDING = 0xEA1C;
    public static final int TAG_PAGE_NAME = 285;
    public static final int TAG_PAGE_NUMBER = 297;
    public static final int TAG_PANASONIC_TITLE = 50898;
    public static final int TAG_PANASONIC_TITLE_2 = 50899;
    public static final int TAG_PHOTOMETRIC_INTERPRETATION = 0x106;
    public static final int TAG_PHOTOSHOP_SETTINGS = 0x8649;
    public static final int TAG_PLANAR_CONFIGURATION = 284;
    public static final int TAG_PREDICTOR = 317;
    public static final int TAG_PRESSURE = 0x9402;
    public static final int TAG_PRIMARY_CHROMATICITIES = 0x13F;
    public static final int TAG_PRINT_IMAGE_MATCHING_INFO = 50341;
    public static final int TAG_RATING = 0x4746;
    public static final int TAG_RATING_PERCENT = 0x4749;
    public static final int TAG_RECOMMENDED_EXPOSURE_INDEX = 0x8832;
    public static final int TAG_REFERENCE_BLACK_WHITE = 532;
    public static final int TAG_RELATED_IMAGE_FILE_FORMAT = 0x1000;
    public static final int TAG_RELATED_IMAGE_HEIGHT = 0x1002;
    public static final int TAG_RELATED_IMAGE_WIDTH = 0x1001;
    public static final int TAG_RELATED_SOUND_FILE = 0xA004;
    public static final int TAG_RESOLUTION_UNIT = 296;
    public static final int TAG_ROWS_PER_STRIP = 278;
    public static final int TAG_SAMPLES_PER_PIXEL = 277;
    public static final int TAG_SAMPLE_FORMAT = 339;
    public static final int TAG_SATURATION = 0xA409;
    public static final int TAG_SCENE_CAPTURE_TYPE = 0xA406;
    public static final int TAG_SCENE_TYPE = 0xA301;
    public static final int TAG_SECURITY_CLASSIFICATION = 0x9212;
    public static final int TAG_SELF_TIMER_MODE_TIFF_EP = 0x882B;
    public static final int TAG_SENSING_METHOD = 0xA217;
    public static final int TAG_SENSITIVITY_TYPE = 0x8830;
    public static final int TAG_SHARPNESS = 0xA40A;
    public static final int TAG_SHUTTER_SPEED = 0x9201;
    public static final int TAG_SOFTWARE = 305;
    public static final int TAG_SPATIAL_FREQ_RESPONSE = 0xA20C;
    public static final int TAG_SPATIAL_FREQ_RESPONSE_TIFF_EP = 0x920C;
    public static final int TAG_SPECTRAL_SENSITIVITY = 0x8824;
    public static final int TAG_STANDARD_ID_TIFF_EP = 0x9216;
    public static final int TAG_STANDARD_OUTPUT_SENSITIVITY = 0x8831;
    public static final int TAG_STRIP_BYTE_COUNTS = 279;
    public static final int TAG_STRIP_OFFSETS = 273;
    public static final int TAG_STRIP_ROW_COUNTS = 0x22F;
    public static final int TAG_SUBFILE_TYPE = 0xFF;
    public static final int TAG_SUBJECT_DISTANCE = 0x9206;
    public static final int TAG_SUBJECT_DISTANCE_RANGE = 0xA40C;
    public static final int TAG_SUBJECT_LOCATION = 0xA214;
    public static final int TAG_SUBJECT_LOCATION_TIFF_EP = 0x9214;
    public static final int TAG_SUBSECOND_TIME = 0x9290;
    public static final int TAG_SUBSECOND_TIME_DIGITIZED = 0x9292;
    public static final int TAG_SUBSECOND_TIME_ORIGINAL = 0x9291;
    public static final int TAG_SUB_IFD_OFFSET = 330;
    public static final int TAG_TEMPERATURE = 0x9400;
    public static final int TAG_THRESHOLDING = 0x107;
    public static final int TAG_TILE_BYTE_COUNTS = 325;
    public static final int TAG_TILE_LENGTH = 323;
    public static final int TAG_TILE_OFFSETS = 324;
    public static final int TAG_TILE_WIDTH = 322;
    public static final int TAG_TIME_ZONE = 0x9010;
    public static final int TAG_TIME_ZONE_DIGITIZED = 0x9012;
    public static final int TAG_TIME_ZONE_OFFSET_TIFF_EP = 0x882A;
    public static final int TAG_TIME_ZONE_ORIGINAL = 0x9011;
    public static final int TAG_TRANSFER_FUNCTION = 301;
    public static final int TAG_TRANSFER_RANGE = 342;
    public static final int TAG_USER_COMMENT = 37510;
    public static final int TAG_WATER_DEPTH = 0x9403;
    public static final int TAG_WHITE_BALANCE = 0x9208;
    public static final int TAG_WHITE_BALANCE_MODE = 0xA403;
    public static final int TAG_WHITE_POINT = 318;
    public static final int TAG_WIN_AUTHOR = 40093;
    public static final int TAG_WIN_COMMENT = 40092;
    public static final int TAG_WIN_KEYWORDS = 40094;
    public static final int TAG_WIN_SUBJECT = 40095;
    public static final int TAG_WIN_TITLE = 40091;
    public static final int TAG_X_RESOLUTION = 282;
    public static final int TAG_YCBCR_COEFFICIENTS = 529;
    public static final int TAG_YCBCR_POSITIONING = 531;
    public static final int TAG_YCBCR_SUBSAMPLING = 530;
    public static final int TAG_Y_RESOLUTION = 283;

    public static void addExifTagNames(HashMap hashMap0) {
        com.apollographql.apollo.api.b.z(1, hashMap0, "Interoperability Index", 2, "Interoperability Version");
        com.apollographql.apollo.api.b.z(0xFE, hashMap0, "New Subfile Type", 0xFF, "Subfile Type");
        com.apollographql.apollo.api.b.z(0x100, hashMap0, "Image Width", 0x101, "Image Height");
        com.apollographql.apollo.api.b.z(0x102, hashMap0, "Bits Per Sample", 0x103, "Compression");
        com.apollographql.apollo.api.b.z(0x106, hashMap0, "Photometric Interpretation", 0x107, "Thresholding");
        com.apollographql.apollo.api.b.z(0x10A, hashMap0, "Fill Order", 0x10D, "Document Name");
        com.apollographql.apollo.api.b.z(270, hashMap0, "Image Description", 0x10F, "Make");
        com.apollographql.apollo.api.b.z(0x110, hashMap0, "Model", 273, "Strip Offsets");
        com.apollographql.apollo.api.b.z(274, hashMap0, "Orientation", 277, "Samples Per Pixel");
        com.apollographql.apollo.api.b.z(278, hashMap0, "Rows Per Strip", 279, "Strip Byte Counts");
        com.apollographql.apollo.api.b.z(280, hashMap0, "Minimum Sample Value", 281, "Maximum Sample Value");
        com.apollographql.apollo.api.b.z(282, hashMap0, "X Resolution", 283, "Y Resolution");
        com.apollographql.apollo.api.b.z(284, hashMap0, "Planar Configuration", 285, "Page Name");
        com.apollographql.apollo.api.b.z(296, hashMap0, "Resolution Unit", 297, "Page Number");
        com.apollographql.apollo.api.b.z(301, hashMap0, "Transfer Function", 305, "Software");
        com.apollographql.apollo.api.b.z(306, hashMap0, "Date/Time", 315, "Artist");
        com.apollographql.apollo.api.b.z(317, hashMap0, "Predictor", 316, "Host Computer");
        com.apollographql.apollo.api.b.z(318, hashMap0, "White Point", 0x13F, "Primary Chromaticities");
        com.apollographql.apollo.api.b.z(322, hashMap0, "Tile Width", 323, "Tile Length");
        com.apollographql.apollo.api.b.z(324, hashMap0, "Tile Offsets", 325, "Tile Byte Counts");
        com.apollographql.apollo.api.b.z(330, hashMap0, "Sub IFD Pointer(s)", 338, "Extra Samples");
        com.apollographql.apollo.api.b.z(339, hashMap0, "Sample Format", 342, "Transfer Range");
        com.apollographql.apollo.api.b.z(347, hashMap0, "JPEG Tables", 0x200, "JPEG Proc");
        com.apollographql.apollo.api.b.z(0x203, hashMap0, "JPEG Restart Interval", 0x205, "JPEG Lossless Predictors");
        com.apollographql.apollo.api.b.z(0x206, hashMap0, "JPEG Point Transforms", 0x207, "JPEGQ Tables");
        com.apollographql.apollo.api.b.z(520, hashMap0, "JPEGDC Tables", 0x209, "JPEGAC Tables");
        com.apollographql.apollo.api.b.z(529, hashMap0, "YCbCr Coefficients", 530, "YCbCr Sub-Sampling");
        com.apollographql.apollo.api.b.z(531, hashMap0, "YCbCr Positioning", 532, "Reference Black/White");
        com.apollographql.apollo.api.b.z(0x22F, hashMap0, "Strip Row Counts", 700, "Application Notes");
        com.apollographql.apollo.api.b.z(0x1000, hashMap0, "Related Image File Format", 0x1001, "Related Image Width");
        com.apollographql.apollo.api.b.z(0x1002, hashMap0, "Related Image Height", 0x4746, "Rating");
        com.apollographql.apollo.api.b.z(0x4749, hashMap0, "Rating Percent", 0x828D, "CFA Repeat Pattern Dim");
        com.apollographql.apollo.api.b.z(0x828E, hashMap0, "CFA Pattern", 0x828F, "Battery Level");
        com.apollographql.apollo.api.b.z(0x8298, hashMap0, "Copyright", 0x829A, "Exposure Time");
        com.apollographql.apollo.api.b.z(0x829D, hashMap0, "F-Number", 0x83BB, "IPTC/NAA");
        com.apollographql.apollo.api.b.z(0x8649, hashMap0, "Photoshop Settings", 0x8773, "Inter Color Profile");
        com.apollographql.apollo.api.b.z(34850, hashMap0, "Exposure Program", 0x8824, "Spectral Sensitivity");
        com.apollographql.apollo.api.b.z(0x8827, hashMap0, "ISO Speed Ratings", 0x8828, "Opto-electric Conversion Function (OECF)");
        com.apollographql.apollo.api.b.z(0x8829, hashMap0, "Interlace", 0x882A, "Time Zone Offset");
        com.apollographql.apollo.api.b.z(0x882B, hashMap0, "Self Timer Mode", 0x8830, "Sensitivity Type");
        com.apollographql.apollo.api.b.z(0x8831, hashMap0, "Standard Output Sensitivity", 0x8832, "Recommended Exposure Index");
        com.apollographql.apollo.api.b.z(0x8833, hashMap0, "ISO Speed", 0x8834, "ISO Speed Latitude yyy");
        com.apollographql.apollo.api.b.z(0x8835, hashMap0, "ISO Speed Latitude zzz", 0x9000, "Exif Version");
        com.apollographql.apollo.api.b.z(0x9003, hashMap0, "Date/Time Original", 0x9004, "Date/Time Digitized");
        com.apollographql.apollo.api.b.z(0x9010, hashMap0, "Time Zone", 0x9011, "Time Zone Original");
        com.apollographql.apollo.api.b.z(0x9012, hashMap0, "Time Zone Digitized", 0x9101, "Components Configuration");
        com.apollographql.apollo.api.b.z(0x9102, hashMap0, "Compressed Bits Per Pixel", 0x9201, "Shutter Speed Value");
        com.apollographql.apollo.api.b.z(0x9202, hashMap0, "Aperture Value", 0x9203, "Brightness Value");
        com.apollographql.apollo.api.b.z(0x9204, hashMap0, "Exposure Bias Value", 0x9205, "Max Aperture Value");
        com.apollographql.apollo.api.b.z(0x9206, hashMap0, "Subject Distance", 0x9207, "Metering Mode");
        com.apollographql.apollo.api.b.z(0x9208, hashMap0, "White Balance", 0x9209, "Flash");
        com.apollographql.apollo.api.b.z(0x920A, hashMap0, "Focal Length", 0x920B, "Flash Energy");
        com.apollographql.apollo.api.b.z(0x920C, hashMap0, "Spatial Frequency Response", 0x920D, "Noise");
        com.apollographql.apollo.api.b.z(0x920E, hashMap0, "Focal Plane X Resolution", 0x920F, "Focal Plane Y Resolution");
        com.apollographql.apollo.api.b.z(0x9211, hashMap0, "Image Number", 0x9212, "Security Classification");
        com.apollographql.apollo.api.b.z(0x9213, hashMap0, "Image History", 0x9214, "Subject Location");
        com.apollographql.apollo.api.b.z(0x9215, hashMap0, "Exposure Index", 0x9216, "TIFF/EP Standard ID");
        com.apollographql.apollo.api.b.z(37500, hashMap0, "Makernote", 37510, "User Comment");
        com.apollographql.apollo.api.b.z(0x9290, hashMap0, "Sub-Sec Time", 0x9291, "Sub-Sec Time Original");
        com.apollographql.apollo.api.b.z(0x9292, hashMap0, "Sub-Sec Time Digitized", 0x9400, "Temperature");
        com.apollographql.apollo.api.b.z(0x9401, hashMap0, "Humidity", 0x9402, "Pressure");
        com.apollographql.apollo.api.b.z(0x9403, hashMap0, "Water Depth", 0x9404, "Acceleration");
        com.apollographql.apollo.api.b.z(0x9405, hashMap0, "Camera Elevation Angle", 40091, "Windows XP Title");
        com.apollographql.apollo.api.b.z(40092, hashMap0, "Windows XP Comment", 40093, "Windows XP Author");
        com.apollographql.apollo.api.b.z(40094, hashMap0, "Windows XP Keywords", 40095, "Windows XP Subject");
        com.apollographql.apollo.api.b.z(0xA000, hashMap0, "FlashPix Version", 0xA001, "Color Space");
        com.apollographql.apollo.api.b.z(0xA002, hashMap0, "Exif Image Width", 0xA003, "Exif Image Height");
        com.apollographql.apollo.api.b.z(0xA004, hashMap0, "Related Sound File", 0xA20B, "Flash Energy");
        com.apollographql.apollo.api.b.z(0xA20C, hashMap0, "Spatial Frequency Response", 0xA20E, "Focal Plane X Resolution");
        com.apollographql.apollo.api.b.z(0xA20F, hashMap0, "Focal Plane Y Resolution", 0xA210, "Focal Plane Resolution Unit");
        com.apollographql.apollo.api.b.z(0xA214, hashMap0, "Subject Location", 0xA215, "Exposure Index");
        com.apollographql.apollo.api.b.z(0xA217, hashMap0, "Sensing Method", 0xA300, "File Source");
        com.apollographql.apollo.api.b.z(0xA301, hashMap0, "Scene Type", 0xA302, "CFA Pattern");
        com.apollographql.apollo.api.b.z(0xA401, hashMap0, "Custom Rendered", 0xA402, "Exposure Mode");
        com.apollographql.apollo.api.b.z(0xA403, hashMap0, "White Balance Mode", 0xA404, "Digital Zoom Ratio");
        com.apollographql.apollo.api.b.z(0xA405, hashMap0, "Focal Length 35", 0xA406, "Scene Capture Type");
        com.apollographql.apollo.api.b.z(0xA407, hashMap0, "Gain Control", 0xA408, "Contrast");
        com.apollographql.apollo.api.b.z(0xA409, hashMap0, "Saturation", 0xA40A, "Sharpness");
        com.apollographql.apollo.api.b.z(0xA40B, hashMap0, "Device Setting Description", 0xA40C, "Subject Distance Range");
        com.apollographql.apollo.api.b.z(0xA420, hashMap0, "Unique Image ID", 0xA430, "Camera Owner Name");
        com.apollographql.apollo.api.b.z(42033, hashMap0, "Body Serial Number", 42034, "Lens Specification");
        com.apollographql.apollo.api.b.z(42035, hashMap0, "Lens Make", 42036, "Lens Model");
        com.apollographql.apollo.api.b.z(42037, hashMap0, "Lens Serial Number", 0xA500, "Gamma");
        com.apollographql.apollo.api.b.z(50341, hashMap0, "Print Image Matching (PIM) Info", 50898, "Panasonic Title");
        com.apollographql.apollo.api.b.z(50899, hashMap0, "Panasonic Title (2)", 0xEA1C, "Padding");
        hashMap0.put(65002, "Lens");
    }
}

