package r1;

import java.util.Arrays;
import java.util.HashMap;

public final class h {
    public int a;
    public final k b;
    public final j c;
    public final i d;
    public final l e;
    public HashMap f;

    public h() {
        k k0 = new k();  // initializer: Ljava/lang/Object;-><init>()V
        k0.a = 0;
        k0.b = 0;
        k0.c = 1.0f;
        k0.d = NaNf;
        this.b = k0;
        j j0 = new j();  // initializer: Ljava/lang/Object;-><init>()V
        j0.a = -1;
        j0.b = 0;
        j0.c = -1;
        j0.d = NaNf;
        j0.e = NaNf;
        j0.f = NaNf;
        j0.g = -1;
        j0.h = null;
        j0.i = -1;
        this.c = j0;
        i i0 = new i();  // initializer: Ljava/lang/Object;-><init>()V
        i0.a = false;
        i0.d = -1;
        i0.e = -1;
        i0.f = -1.0f;
        i0.g = true;
        i0.h = -1;
        i0.i = -1;
        i0.j = -1;
        i0.k = -1;
        i0.l = -1;
        i0.m = -1;
        i0.n = -1;
        i0.o = -1;
        i0.p = -1;
        i0.q = -1;
        i0.r = -1;
        i0.s = -1;
        i0.t = -1;
        i0.u = -1;
        i0.v = -1;
        i0.w = 0.5f;
        i0.x = 0.5f;
        i0.y = null;
        i0.z = -1;
        i0.A = 0;
        i0.B = 0.0f;
        i0.C = -1;
        i0.D = -1;
        i0.E = -1;
        i0.F = 0;
        i0.G = 0;
        i0.H = 0;
        i0.I = 0;
        i0.J = 0;
        i0.K = 0;
        i0.L = 0;
        i0.M = 0x80000000;
        i0.N = 0x80000000;
        i0.O = 0x80000000;
        i0.P = 0x80000000;
        i0.Q = 0x80000000;
        i0.R = 0x80000000;
        i0.S = 0x80000000;
        i0.T = -1.0f;
        i0.U = -1.0f;
        i0.V = 0;
        i0.W = 0;
        i0.X = 0;
        i0.Y = 0;
        i0.Z = 0;
        i0.a0 = 0;
        i0.b0 = 0;
        i0.c0 = 0;
        i0.d0 = 1.0f;
        i0.e0 = 1.0f;
        i0.f0 = -1;
        i0.g0 = 0;
        i0.h0 = -1;
        i0.l0 = false;
        i0.m0 = false;
        i0.n0 = true;
        i0.o0 = 0;
        this.d = i0;
        l l0 = new l();  // initializer: Ljava/lang/Object;-><init>()V
        l0.a = 0.0f;
        l0.b = 0.0f;
        l0.c = 0.0f;
        l0.d = 1.0f;
        l0.e = 1.0f;
        l0.f = NaNf;
        l0.g = NaNf;
        l0.h = -1;
        l0.i = 0.0f;
        l0.j = 0.0f;
        l0.k = 0.0f;
        l0.l = false;
        l0.m = 0.0f;
        this.e = l0;
        this.f = new HashMap();
    }

    public final void a(d d0) {
        i i0 = this.d;
        d0.e = i0.h;
        d0.f = i0.i;
        d0.g = i0.j;
        d0.h = i0.k;
        d0.i = i0.l;
        d0.j = i0.m;
        d0.k = i0.n;
        d0.l = i0.o;
        d0.m = i0.p;
        d0.n = i0.q;
        d0.o = i0.r;
        d0.s = i0.s;
        d0.t = i0.t;
        d0.u = i0.u;
        d0.v = i0.v;
        d0.leftMargin = i0.F;
        d0.rightMargin = i0.G;
        d0.topMargin = i0.H;
        d0.bottomMargin = i0.I;
        d0.A = i0.R;
        d0.B = i0.Q;
        d0.x = i0.N;
        d0.z = i0.P;
        d0.E = i0.w;
        d0.F = i0.x;
        d0.p = i0.z;
        d0.q = i0.A;
        d0.r = i0.B;
        d0.G = i0.y;
        d0.T = i0.C;
        d0.U = i0.D;
        d0.I = i0.T;
        d0.H = i0.U;
        d0.K = i0.W;
        d0.J = i0.V;
        d0.W = i0.l0;
        d0.X = i0.m0;
        d0.L = i0.X;
        d0.M = i0.Y;
        d0.P = i0.Z;
        d0.Q = i0.a0;
        d0.N = i0.b0;
        d0.O = i0.c0;
        d0.R = i0.d0;
        d0.S = i0.e0;
        d0.V = i0.E;
        d0.c = i0.f;
        d0.a = i0.d;
        d0.b = i0.e;
        d0.width = i0.b;
        d0.height = i0.c;
        String s = i0.k0;
        if(s != null) {
            d0.Y = s;
        }
        d0.Z = i0.o0;
        d0.setMarginStart(i0.K);
        d0.setMarginEnd(i0.J);
        d0.a();
    }

    @Override
    public final Object clone() {
        Object object0 = new h();
        i i0 = object0.d;
        i0.getClass();
        i i1 = this.d;
        i0.a = i1.a;
        i0.b = i1.b;
        i0.c = i1.c;
        i0.d = i1.d;
        i0.e = i1.e;
        i0.f = i1.f;
        i0.g = i1.g;
        i0.h = i1.h;
        i0.i = i1.i;
        i0.j = i1.j;
        i0.k = i1.k;
        i0.l = i1.l;
        i0.m = i1.m;
        i0.n = i1.n;
        i0.o = i1.o;
        i0.p = i1.p;
        i0.q = i1.q;
        i0.r = i1.r;
        i0.s = i1.s;
        i0.t = i1.t;
        i0.u = i1.u;
        i0.v = i1.v;
        i0.w = i1.w;
        i0.x = i1.x;
        i0.y = i1.y;
        i0.z = i1.z;
        i0.A = i1.A;
        i0.B = i1.B;
        i0.C = i1.C;
        i0.D = i1.D;
        i0.E = i1.E;
        i0.F = i1.F;
        i0.G = i1.G;
        i0.H = i1.H;
        i0.I = i1.I;
        i0.J = i1.J;
        i0.K = i1.K;
        i0.L = i1.L;
        i0.M = i1.M;
        i0.N = i1.N;
        i0.O = i1.O;
        i0.P = i1.P;
        i0.Q = i1.Q;
        i0.R = i1.R;
        i0.S = i1.S;
        i0.T = i1.T;
        i0.U = i1.U;
        i0.V = i1.V;
        i0.W = i1.W;
        i0.X = i1.X;
        i0.Y = i1.Y;
        i0.Z = i1.Z;
        i0.a0 = i1.a0;
        i0.b0 = i1.b0;
        i0.c0 = i1.c0;
        i0.d0 = i1.d0;
        i0.e0 = i1.e0;
        i0.f0 = i1.f0;
        i0.g0 = i1.g0;
        i0.h0 = i1.h0;
        i0.k0 = i1.k0;
        int[] arr_v = i1.i0;
        i0.i0 = arr_v == null || i1.j0 != null ? null : Arrays.copyOf(arr_v, arr_v.length);
        i0.j0 = i1.j0;
        i0.l0 = i1.l0;
        i0.m0 = i1.m0;
        i0.n0 = i1.n0;
        i0.o0 = i1.o0;
        object0.c.getClass();
        this.c.getClass();
        object0.c.a = this.c.a;
        object0.c.c = this.c.c;
        object0.c.e = this.c.e;
        object0.c.d = this.c.d;
        object0.b.a = this.b.a;
        object0.b.c = this.b.c;
        object0.b.d = this.b.d;
        object0.b.b = this.b.b;
        object0.e.getClass();
        this.e.getClass();
        object0.e.a = this.e.a;
        object0.e.b = this.e.b;
        object0.e.c = this.e.c;
        object0.e.d = this.e.d;
        object0.e.e = this.e.e;
        object0.e.f = this.e.f;
        object0.e.g = this.e.g;
        object0.e.h = this.e.h;
        object0.e.i = this.e.i;
        object0.e.j = this.e.j;
        object0.e.k = this.e.k;
        object0.e.l = this.e.l;
        object0.e.m = this.e.m;
        object0.a = this.a;
        return object0;
    }
}

