package com.drew.metadata.wav;

import com.drew.metadata.b;
import java.util.HashMap;

public class WavDirectory extends b {
    public static final String CHUNK_DATA = "data";
    public static final String CHUNK_FORMAT = "fmt ";
    public static final String FORMAT = "WAVE";
    public static final String LIST_INFO = "INFO";
    public static final int TAG_ARTIST = 7;
    public static final int TAG_BITS_PER_SAMPLE = 6;
    public static final int TAG_BLOCK_ALIGNMENT = 5;
    public static final int TAG_BYTES_PER_SEC = 4;
    public static final int TAG_CHANNELS = 2;
    public static final int TAG_COMMENTS = 13;
    public static final int TAG_COPYRIGHT = 14;
    public static final int TAG_DATE_CREATED = 11;
    public static final int TAG_DURATION = 16;
    public static final int TAG_FORMAT = 1;
    public static final int TAG_GENRE = 12;
    public static final int TAG_PRODUCT = 9;
    public static final int TAG_SAMPLES_PER_SEC = 3;
    public static final int TAG_SOFTWARE = 15;
    public static final int TAG_TITLE = 8;
    public static final int TAG_TRACK_NUMBER = 10;
    static final transient HashMap _audioEncodingMap;
    static final transient HashMap _tagIntegerMap;
    private static final HashMap _tagNameMap;

    static {
        HashMap hashMap0 = new HashMap();
        WavDirectory._tagNameMap = hashMap0;
        HashMap hashMap1 = new HashMap();
        WavDirectory._tagIntegerMap = hashMap1;
        HashMap hashMap2 = new HashMap();
        WavDirectory._audioEncodingMap = hashMap2;
        Integer integer0 = 7;
        hashMap1.put("IART", integer0);
        Integer integer1 = 8;
        hashMap1.put("INAM", integer1);
        Integer integer2 = 9;
        hashMap1.put("IPRD", integer2);
        Integer integer3 = 10;
        hashMap1.put("ITRK", integer3);
        Integer integer4 = 11;
        hashMap1.put("ICRD", integer4);
        Integer integer5 = 12;
        hashMap1.put("IGNR", integer5);
        Integer integer6 = 13;
        hashMap1.put("ICMT", integer6);
        Integer integer7 = 14;
        hashMap1.put("ICOP", integer7);
        Integer integer8 = 15;
        hashMap1.put("ISFT", integer8);
        Integer integer9 = 1;
        hashMap0.put(integer9, "Format");
        Integer integer10 = 2;
        hashMap0.put(integer10, "Channels");
        Integer integer11 = 3;
        hashMap0.put(integer11, "Samples Per Second");
        Integer integer12 = 4;
        hashMap0.put(integer12, "Bytes Per Second");
        Integer integer13 = 5;
        hashMap0.put(integer13, "Block Alignment");
        Integer integer14 = 6;
        hashMap0.put(integer14, "Bits Per Sample");
        hashMap0.put(integer0, "Artist");
        hashMap0.put(integer1, "Title");
        hashMap0.put(integer2, "Product");
        hashMap0.put(integer3, "Track Number");
        hashMap0.put(integer4, "Date Created");
        hashMap0.put(integer5, "Genre");
        hashMap0.put(integer6, "Comments");
        hashMap0.put(integer7, "Copyright");
        hashMap0.put(integer8, "Software");
        hashMap0.put(16, "Duration");
        hashMap2.put(integer9, "Microsoft PCM");
        hashMap2.put(integer10, "Microsoft ADPCM");
        hashMap2.put(integer11, "Microsoft IEEE float");
        hashMap2.put(integer12, "Compaq VSELP");
        hashMap2.put(integer13, "IBM CVSD");
        hashMap2.put(integer14, "Microsoft a-Law");
        hashMap2.put(integer0, "Microsoft u-Law");
        hashMap2.put(integer1, "Microsoft DTS");
        hashMap2.put(integer2, "DRM");
        hashMap2.put(integer3, "WMA 9 Speech");
        hashMap2.put(integer4, "Microsoft Windows Media RT Voice");
        hashMap2.put(16, "OKI-ADPCM");
        com.apollographql.apollo.api.b.z(17, hashMap2, "Intel IMA/DVI-ADPCM", 18, "Videologic Mediaspace ADPCM");
        com.apollographql.apollo.api.b.z(19, hashMap2, "Sierra ADPCM", 20, "Antex G.723 ADPCM");
        com.apollographql.apollo.api.b.z(21, hashMap2, "DSP Solutions DIGISTD", 22, "DSP Solutions DIGIFIX");
        com.apollographql.apollo.api.b.z(23, hashMap2, "Dialoic OKI ADPCM", 24, "Media Vision ADPCM");
        com.apollographql.apollo.api.b.z(25, hashMap2, "HP CU", 26, "HP Dynamic Voice");
        com.apollographql.apollo.api.b.z(0x20, hashMap2, "Yamaha ADPCM", 33, "SONARC Speech Compression");
        com.apollographql.apollo.api.b.z(34, hashMap2, "DSP Group True Speech", 35, "Echo Speech Corp.");
        com.apollographql.apollo.api.b.z(36, hashMap2, "Virtual Music Audiofile AF36", 37, "Audio Processing Tech.");
        com.apollographql.apollo.api.b.z(38, hashMap2, "Virtual Music Audiofile AF10", 39, "Aculab Prosody 1612");
        com.apollographql.apollo.api.b.z(40, hashMap2, "Merging Tech. LRC", 0x30, "Dolby AC2");
        com.apollographql.apollo.api.b.z(49, hashMap2, "Microsoft GSM610", 50, "MSN Audio");
        com.apollographql.apollo.api.b.z(51, hashMap2, "Antex ADPCME", 52, "Control Resources VQLPC");
        com.apollographql.apollo.api.b.z(53, hashMap2, "DSP Solutions DIGIREAL", 54, "DSP Solutions DIGIADPCM");
        com.apollographql.apollo.api.b.z(55, hashMap2, "Control Resources CR10", 56, "Natural MicroSystems VBX ADPCM");
        com.apollographql.apollo.api.b.z(57, hashMap2, "Crystal Semiconductor IMA ADPCM", 58, "Echo Speech ECHOSC3");
        com.apollographql.apollo.api.b.z(59, hashMap2, "Rockwell ADPCM", 60, "Rockwell DIGITALK");
        com.apollographql.apollo.api.b.z(61, hashMap2, "Xebec Multimedia", 0x40, "Antex G.721 ADPCM");
        com.apollographql.apollo.api.b.z(65, hashMap2, "Antex G.728 CELP", 66, "Microsoft MSG723");
        com.apollographql.apollo.api.b.z(67, hashMap2, "IBM AVC ADPCM", 69, "ITU-T G.726");
        com.apollographql.apollo.api.b.z(80, hashMap2, "Microsoft MPEG", 81, "RT23 or PAC");
        com.apollographql.apollo.api.b.z(82, hashMap2, "InSoft RT24", 83, "InSoft PAC");
        com.apollographql.apollo.api.b.z(85, hashMap2, "MP3", 89, "Cirrus");
        com.apollographql.apollo.api.b.z(0x60, hashMap2, "Cirrus Logic", 97, "ESS Tech. PCM");
        com.apollographql.apollo.api.b.z(98, hashMap2, "Voxware Inc.", 99, "Canopus ATRAC");
        com.apollographql.apollo.api.b.z(100, hashMap2, "APICOM G.726 ADPCM", 101, "APICOM G.722 ADPCM");
        com.apollographql.apollo.api.b.z(102, hashMap2, "Microsoft DSAT", 103, "Micorsoft DSAT DISPLAY");
        com.apollographql.apollo.api.b.z(105, hashMap2, "Voxware Byte Aligned", 0x70, "Voxware AC8");
        com.apollographql.apollo.api.b.z(0x71, hashMap2, "Voxware AC10", 0x72, "Voxware AC16");
        com.apollographql.apollo.api.b.z(0x73, hashMap2, "Voxware AC20", 0x74, "Voxware MetaVoice");
        com.apollographql.apollo.api.b.z(0x75, hashMap2, "Voxware MetaSound", 0x76, "Voxware RT29HW");
        com.apollographql.apollo.api.b.z(0x77, hashMap2, "Voxware VR12", 120, "Voxware VR18");
        com.apollographql.apollo.api.b.z(0x79, hashMap2, "Voxware TQ40", 0x7A, "Voxware SC3");
        com.apollographql.apollo.api.b.z(0x7B, hashMap2, "Voxware SC3", 0x80, "Soundsoft");
        com.apollographql.apollo.api.b.z(0x81, hashMap2, "Voxware TQ60", 130, "Microsoft MSRT24");
        com.apollographql.apollo.api.b.z(0x83, hashMap2, "AT&T G.729A", 0x84, "Motion Pixels MVI MV12");
        com.apollographql.apollo.api.b.z(0x85, hashMap2, "DataFusion G.726", 0x86, "DataFusion GSM610");
        com.apollographql.apollo.api.b.z(0x88, hashMap2, "Iterated Systems Audio", 0x89, "Onlive");
        com.apollographql.apollo.api.b.z(0x8A, hashMap2, "Multitude, Inc. FT SX20", 0x8B, "Infocom ITS A/S G.721 ADPCM");
        com.apollographql.apollo.api.b.z(140, hashMap2, "Convedia G729", 0x8D, "Not specified congruency, Inc.");
        com.apollographql.apollo.api.b.z(0x91, hashMap2, "Siemens SBC24", 0x92, "Sonic Foundry Dolby AC3 APDIF");
        com.apollographql.apollo.api.b.z(0x93, hashMap2, "MediaSonic G.723", 0x94, "Aculab Prosody 8kbps");
        com.apollographql.apollo.api.b.z(0x97, hashMap2, "ZyXEL ADPCM", 0x98, "Philips LPCBB");
        com.apollographql.apollo.api.b.z(0x99, hashMap2, "Studer Professional Audio Packed", 0xA0, "Malden PhonyTalk");
        com.apollographql.apollo.api.b.z(0xA1, hashMap2, "Racal Recorder GSM", 0xA2, "Racal Recorder G720.a");
        com.apollographql.apollo.api.b.z(0xA3, hashMap2, "Racal G723.1", 0xA4, "Racal Tetra ACELP");
        com.apollographql.apollo.api.b.z(0xB0, hashMap2, "NEC AAC NEC Corporation", 0xFF, "AAC");
        com.apollographql.apollo.api.b.z(0x100, hashMap2, "Rhetorex ADPCM", 0x101, "IBM u-Law");
        com.apollographql.apollo.api.b.z(0x102, hashMap2, "IBM a-Law", 0x103, "IBM ADPCM");
        com.apollographql.apollo.api.b.z(273, hashMap2, "Vivo G.723", 274, "Vivo Siren");
        com.apollographql.apollo.api.b.z(0x120, hashMap2, "Philips Speech Processing CELP", 289, "Philips Speech Processing GRUNDIG");
        com.apollographql.apollo.api.b.z(291, hashMap2, "Digital G.723", 293, "Sanyo LD ADPCM");
        com.apollographql.apollo.api.b.z(304, hashMap2, "Sipro Lab ACEPLNET", 305, "Sipro Lab ACELP4800");
        com.apollographql.apollo.api.b.z(306, hashMap2, "Sipro Lab ACELP8V3", 307, "Sipro Lab G.729");
        com.apollographql.apollo.api.b.z(308, hashMap2, "Sipro Lab G.729A", 309, "Sipro Lab Kelvin");
        com.apollographql.apollo.api.b.z(310, hashMap2, "VoiceAge AMR", 320, "Dictaphone G.726 ADPCM");
        com.apollographql.apollo.api.b.z(0x150, hashMap2, "Qualcomm PureVoice", 337, "Qualcomm HalfRate");
        com.apollographql.apollo.api.b.z(341, hashMap2, "Ring Zero Systems TUBGSM", 0x160, "Microsoft Audio1");
        com.apollographql.apollo.api.b.z(353, hashMap2, "Windows Media Audio V2 V7 V8 V9 / DivX audio (WMA) / Alex AC3 Audio", 354, "Windows Media Audio Professional V9");
        com.apollographql.apollo.api.b.z(355, hashMap2, "Windows Media Audio Lossless V9", 356, "WMA Pro over S/PDIF");
        com.apollographql.apollo.api.b.z(0x170, hashMap2, "UNISYS NAP ADPCM", 369, "UNISYS NAP ULAW");
        com.apollographql.apollo.api.b.z(370, hashMap2, "UNISYS NAP ALAW", 371, "UNISYS NAP 16K");
        com.apollographql.apollo.api.b.z(372, hashMap2, "MM SYCOM ACM SYC008 SyCom Technologies", 373, "MM SYCOM ACM SYC701 G726L SyCom Technologies");
        com.apollographql.apollo.api.b.z(374, hashMap2, "MM SYCOM ACM SYC701 CELP54 SyCom Technologies", 375, "MM SYCOM ACM SYC701 CELP68 SyCom Technologies");
        com.apollographql.apollo.api.b.z(376, hashMap2, "Knowledge Adventure ADPCM", 0x180, "Fraunhofer IIS MPEG2AAC");
        com.apollographql.apollo.api.b.z(400, hashMap2, "Digital Theater Systems DTS DS", 0x200, "Creative Labs ADPCM");
        com.apollographql.apollo.api.b.z(0x202, hashMap2, "Creative Labs FASTSPEECH8", 0x203, "Creative Labs FASTSPEECH10");
        com.apollographql.apollo.api.b.z(0x210, hashMap2, "UHER ADPCM", 533, "Ulead DV ACM");
        com.apollographql.apollo.api.b.z(534, hashMap2, "Ulead DV ACM", 0x220, "Quarterdeck Corp.");
        com.apollographql.apollo.api.b.z(560, hashMap2, "I-Link VC", 0x240, "Aureal Semiconductor Raw Sport");
        com.apollographql.apollo.api.b.z(577, hashMap2, "ESST AC3", 0x250, "Interactive Products HSX");
        com.apollographql.apollo.api.b.z(593, hashMap2, "Interactive Products RPELP", 608, "Consistent CS2");
        com.apollographql.apollo.api.b.z(0x270, hashMap2, "Sony SCX", 625, "Sony SCY");
        com.apollographql.apollo.api.b.z(626, hashMap2, "Sony ATRAC3", 627, "Sony SPC");
        com.apollographql.apollo.api.b.z(640, hashMap2, "TELUM Telum Inc.", 641, "TELUMIA Telum Inc.");
        com.apollographql.apollo.api.b.z(645, hashMap2, "Norcom Voice Systems ADPCM", 0x300, "Fujitsu FM TOWNS SND");
        com.apollographql.apollo.api.b.z(0x301, hashMap2, "Fujitsu (not specified)", 770, "Fujitsu (not specified)");
        com.apollographql.apollo.api.b.z(0x303, hashMap2, "Fujitsu (not specified)", 0x304, "Fujitsu (not specified)");
        com.apollographql.apollo.api.b.z(0x305, hashMap2, "Fujitsu (not specified)", 0x306, "Fujitsu (not specified)");
        com.apollographql.apollo.api.b.z(0x307, hashMap2, "Fujitsu (not specified)", 0x308, "Fujitsu (not specified)");
        com.apollographql.apollo.api.b.z(0x350, hashMap2, "Micronas Semiconductors, Inc. Development", 849, "Micronas Semiconductors, Inc. CELP833");
        com.apollographql.apollo.api.b.z(0x400, hashMap2, "Brooktree Digital", 0x401, "Intel Music Coder (IMC)");
        com.apollographql.apollo.api.b.z(0x402, hashMap2, "Ligos Indeo Audio", 0x450, "QDesign Music");
        com.apollographql.apollo.api.b.z(0x500, hashMap2, "On2 VP7 On2 Technologies", 0x501, "On2 VP6 On2 Technologies");
        com.apollographql.apollo.api.b.z(0x680, hashMap2, "AT&T VME VMPCM", 0x681, "AT&T TCP");
        com.apollographql.apollo.api.b.z(0x700, hashMap2, "YMPEG Alpha (dummy for MPEG-2 compressor)", 0x8AE, "ClearJump LiteWave (lossless)");
        com.apollographql.apollo.api.b.z(0x1000, hashMap2, "Olivetti GSM", 0x1001, "Olivetti ADPCM");
        com.apollographql.apollo.api.b.z(0x1002, hashMap2, "Olivetti CELP", 0x1003, "Olivetti SBC");
        com.apollographql.apollo.api.b.z(4100, hashMap2, "Olivetti OPR", 0x1100, "Lernout & Hauspie");
        com.apollographql.apollo.api.b.z(0x1101, hashMap2, "Lernout & Hauspie CELP codec", 0x1102, "Lernout & Hauspie SBC codec");
        com.apollographql.apollo.api.b.z(0x1103, hashMap2, "Lernout & Hauspie SBC codec", 0x1104, "Lernout & Hauspie SBC codec");
        com.apollographql.apollo.api.b.z(0x1400, hashMap2, "Norris Comm. Inc.", 0x1401, "ISIAudio");
        com.apollographql.apollo.api.b.z(0x1500, hashMap2, "AT&T Soundspace Music Compression", 6172, "VoxWare RT24 speech codec");
        com.apollographql.apollo.api.b.z(6174, hashMap2, "Lucent elemedia AX24000P Music codec", 6513, "Sonic Foundry LOSSLESS");
        com.apollographql.apollo.api.b.z(6521, hashMap2, "Innings Telecom Inc. ADPCM", 0x1C07, "Lucent SX8300P speech codec");
        com.apollographql.apollo.api.b.z(7180, hashMap2, "Lucent SX5363S G.723 compliant codec", 0x1F03, "CUseeMe DigiTalk (ex-Rocwell)");
        com.apollographql.apollo.api.b.z(0x1FC4, hashMap2, "NCT Soft ALF2CD ACM", 0x2000, "FAST Multimedia DVM");
        com.apollographql.apollo.api.b.z(0x2001, hashMap2, "Dolby DTS (Digital Theater System)", 0x2002, "RealAudio 1 / 2 14.4");
        com.apollographql.apollo.api.b.z(0x2003, hashMap2, "RealAudio 1 / 2 28.8", 0x2004, "RealAudio G2 / 8 Cook (low bitrate)");
        com.apollographql.apollo.api.b.z(0x2005, hashMap2, "RealAudio 3 / 4 / 5 Music (DNET)", 0x2006, "RealAudio 10 AAC (RAAC)");
        com.apollographql.apollo.api.b.z(0x2007, hashMap2, "RealAudio 10 AAC+ (RACP)", 0x2500, "Reserved range to 0x2600 Microsoft");
        com.apollographql.apollo.api.b.z(13075, hashMap2, "makeAVIS (ffvfw fake AVI sound from AviSynth scripts)", 16707, "Divio MPEG-4 AAC audio");
        com.apollographql.apollo.api.b.z(0x4201, hashMap2, "Nokia adaptive multirate", 0x4243, "Divio G726 Divio, Inc.");
        com.apollographql.apollo.api.b.z(0x434C, hashMap2, "LEAD Speech", 22092, "LEAD Vorbis");
        com.apollographql.apollo.api.b.z(0x5756, hashMap2, "WavPack Audio", 0x674F, "Ogg Vorbis (mode 1)");
        com.apollographql.apollo.api.b.z(0x6750, hashMap2, "Ogg Vorbis (mode 2)", 0x6751, "Ogg Vorbis (mode 3)");
        com.apollographql.apollo.api.b.z(0x676F, hashMap2, "Ogg Vorbis (mode 1+)", 0x6770, "Ogg Vorbis (mode 2+)");
        com.apollographql.apollo.api.b.z(0x6771, hashMap2, "Ogg Vorbis (mode 3+)", 0x7000, "3COM NBX 3Com Corporation");
        com.apollographql.apollo.api.b.z(0x706D, hashMap2, "FAAD AAC", 0x7A21, "GSM-AMR (CBR, no SID)");
        com.apollographql.apollo.api.b.z(0x7A22, hashMap2, "GSM-AMR (VBR, including SID)", 0xA100, "Comverse Infosys Ltd. G723 1");
        com.apollographql.apollo.api.b.z(0xA101, hashMap2, "Comverse Infosys Ltd. AVQSBC", 0xA102, "Comverse Infosys Ltd. OLDSBC");
        com.apollographql.apollo.api.b.z(0xA103, hashMap2, "Symbol Technologies G729A", 0xA104, "VoiceAge AMR WB VoiceAge Corporation");
        com.apollographql.apollo.api.b.z(0xA105, hashMap2, "Ingenient Technologies Inc. G726", 0xA106, "ISO/MPEG-4 advanced audio Coding");
        com.apollographql.apollo.api.b.z(0xA107, hashMap2, "Encore Software Ltd G726", 0xA109, "Speex ACM Codec xiph.org");
        com.apollographql.apollo.api.b.z(0xDFAC, hashMap2, "DebugMode SonicFoundry Vegas FrameServer ACM Codec", 0xE708, "Unknown -");
        com.apollographql.apollo.api.b.z(0xF1AC, hashMap2, "Free Lossless Audio Codec FLAC", 0xFFFE, "Extensible");
        hashMap2.put(0xFFFF, "Development");
    }

    public WavDirectory() {
        this.setDescriptor(new A4.b(19, this));
    }

    @Override  // com.drew.metadata.b
    public String getName() {
        return "WAV";
    }

    @Override  // com.drew.metadata.b
    public HashMap getTagNameMap() {
        return WavDirectory._tagNameMap;
    }
}

