package com.google.android.gms.internal.gtm;

import java.util.Collections;
import java.util.HashSet;

public abstract class zzeh {
    public static final zzeg zzA;
    public static final zzeg zzB;
    public static final zzeg zzC;
    public static final zzeg zzD;
    public static final zzeg zzE;
    public static final zzeg zzF;
    public static final zzeg zza;
    public static final zzeg zzb;
    public static final zzeg zzc;
    public static final zzeg zzd;
    public static final zzeg zze;
    public static final zzeg zzf;
    public static final zzeg zzg;
    public static final zzeg zzh;
    public static final zzeg zzi;
    public static final zzeg zzj;
    public static final zzeg zzk;
    public static final zzeg zzl;
    public static final zzeg zzm;
    public static final zzeg zzn;
    public static final zzeg zzo;
    public static final zzeg zzp;
    public static final zzeg zzq;
    public static final zzeg zzr;
    public static final zzeg zzs;
    public static final zzeg zzt;
    public static final zzeg zzu;
    public static final zzeg zzv;
    public static final zzeg zzw;
    public static final zzeg zzx;
    public static final zzeg zzy;
    public static final zzeg zzz;

    static {
        Collections.synchronizedSet(new HashSet());
        zzeh.zza = zzeg.zza(Boolean.TRUE, Boolean.TRUE, new zzda());
        zzeh.zzb = zzeg.zza("GAv4", "GAv4-SVC", new zzdj());
        zzeh.zzc = zzeg.zza(2000, 20000, new zzdu());
        Integer integer0 = 100;
        zzeh.zzd = zzeg.zza(integer0, integer0, new zzdw());
        Long long0 = 1800000L;
        zzeh.zze = zzeg.zza(long0, 120000L, new zzdx());
        Long long1 = 5000L;
        zzeh.zzf = zzeg.zza(long1, long1, new zzdy());
        Long long2 = 7200000L;
        zzeh.zzg = zzeg.zza(long2, long2, new zzdv());
        Long long3 = 32400000L;
        zzeh.zzh = zzeg.zza(long3, long3, new zzdz());
        Integer integer1 = 20;
        zzeh.zzi = zzeg.zza(integer1, integer1, new zzea());
        zzeh.zzj = zzeg.zza(integer1, integer1, new zzeb());
        zzeh.zzk = zzeg.zza("http://www.google-analytics.com", "http://www.google-analytics.com", new zzec());
        zzeh.zzl = zzeg.zza("https://ssl.google-analytics.com", "https://ssl.google-analytics.com", new zzed());
        zzeh.zzm = zzeg.zza("/collect", "/collect", new zzee());
        zzeh.zzn = zzeg.zza("/batch", "/batch", new zzcz());
        Integer integer2 = 0x7F4;
        zzeh.zzo = zzeg.zza(integer2, integer2, new zzdb());
        zzeh.zzp = zzeg.zza("BATCH_BY_COUNT", "BATCH_BY_COUNT", new zzdc());
        zzeh.zzq = zzeg.zza("GZIP", "GZIP", new zzdd());
        Integer integer3 = 0x2000;
        zzeh.zzr = zzeg.zza(integer3, integer3, new zzde());
        zzeh.zzs = zzeg.zza(integer3, integer3, new zzdf());
        zzeh.zzt = zzeg.zza(integer3, integer3, new zzdg());
        zzeh.zzu = zzeg.zza("404,502", "404,502", new zzdh());
        Integer integer4 = 3600;
        zzeh.zzv = zzeg.zza(integer4, integer4, new zzdi());
        Integer integer5 = 60000;
        zzeh.zzw = zzeg.zza(integer5, integer5, new zzdk());
        Integer integer6 = 61000;
        zzeh.zzx = zzeg.zza(integer6, integer6, new zzdl());
        Long long4 = 86400000L;
        zzeh.zzy = zzeg.zza(long4, long4, new zzdm());
        Boolean boolean0 = Boolean.FALSE;
        zzeh.zzz = zzeg.zza(boolean0, boolean0, new zzdn());
        Long long5 = 10000L;
        zzeh.zzA = zzeg.zza(long5, long5, new zzdo());
        zzeh.zzB = zzeg.zza(long1, long1, new zzdp());
        zzeh.zzC = zzeg.zza(long0, long0, new zzdq());
        zzeh.zzD = zzeg.zza(long4, long4, new zzdr());
        zzeh.zzE = zzeg.zza(long1, long1, new zzds());
        zzeh.zzF = zzeg.zza(boolean0, boolean0, new zzdt());
    }
}

